name: secure_storage
description: Secure storage adapter backed by flutter_secure_storage.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: 10.3.1
  meta: 1.18.0
