name: realtime_media
description: WebRTC peer media session runtime for sols.stream.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_webrtc: 1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: 1.0.5
