name: signaling
description: Solana on-chain WebRTC signaling for sols.stream
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  solana: 0.32.0+1
  cryptography: 2.9.0

  # packages
  solana_wallet:
    path: ../solana_wallet
